language: ruby
rvm:
- 2.3.1

before_script:
  - npm install -g jshint

# Since bundler is used, the `install` step will run `bundle install` by default.
script: ./script/cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  bundler: true
  directories:
  - tmp/.htmlproofer # cache external link checks
