language: ruby
rvm:
  - 2.5.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      # https://github.com/gjtorikian/html-proofer/issues/376
      # Avoid SSL errors
      - libcurl4-openssl-dev

before_script:
  - npm install -g jshint

script: ./script/cibuild.sh

cache:
  bundler: true
  directories:
    - tmp/.htmlproofer # cache external link checks
