language: ruby
rvm:
- 2.1

install: bundle install --jobs=3 --retry=3
script: jekyll build && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
